version: "3.7"

services:
  lotus:
    image: textile/lotus-devnet:v0.5.3
    ports:
      - 7777:7777
    environment:
      - TEXLOTUSDEVNET_SPEED=1500
      - TEXLOTUSDEVNET_BIGSECTORS=${BIGSECTORS}
      - TEXLOTUSDEVNET_IPFSADDR=/dns4/ipfs/tcp/5001
  ipfs:
    ports:
      - 7070:8080
